package:
  name: spatyper
  version: 1.0.0

source:
  url: https://bitbucket.org/genomicepidemiology/spaTyper/get/1.0.0.tar.gz

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.5
    - kma
    - wget
  run:
    - wget
    - python >=3.5
    - kma
    - cgecore
    - blast
    - tabulate
    - ete3
test:
  commands:
    - spatyper.py -h | grep spatyper.py >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/spatyper
  summary: 'The spaTyper service predicts the Staphylococcus aureus spa type from genome sequences.'
  license: Apache-2.0